# Generated by Django 2.2.6 on 2019-10-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20191023_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicpost',
            name='artist_id',
            field=models.CharField(default='1PYYB5do8WAaHfs3K', max_length=100),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='artist_name',
            field=models.CharField(default='ZYbPR', max_length=100),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='artist_terms',
            field=models.CharField(default='FxSOY', max_length=100),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='song_id',
            field=models.SlugField(default='3yDslad3MvGIYZWJp', unique=True),
        ),
    ]
