# Generated by Django 2.2.6 on 2019-10-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20191023_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicpost',
            name='artist_id',
            field=models.CharField(default='4PVAwZe8m2OLqbGEg', max_length=100),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='artist_name',
            field=models.CharField(default='VDqMu', max_length=100),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='artist_terms',
            field=models.CharField(default='HICMj', max_length=100),
        ),
        migrations.AlterField(
            model_name='musicpost',
            name='song_id',
            field=models.SlugField(default='ABgykzxeBySc4y205', unique=True),
        ),
    ]
